FROM --platform=linux/arm64 node:18-slim as base
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install
ENV APP_ENV=docker

FROM base as api
ENV PORT=80
EXPOSE 8085
CMD [ "npm", "run", "start:api:debug" ]

FROM base as data
ENV PORT=8087
EXPOSE 8087
CMD [ "npm", "run", "start:data:debug" ]